// 4 scene presets

export const SCENES = {
  'deep-ocean': {
    id: 'deep-ocean',
    name: 'Deep Ocean',
    description: 'Abyssal calm',
    audio: {
      rootNote: 'D',
      scale: 'minor-pentatonic',
      droneWaveform: 'sine',
      droneGain: 0.18,
      droneDetune: 6,
      melodyGain: 0.06,
      melodyWaveform: 'sine',
      melodyOctaveLow: 3,
      melodyOctaveHigh: 4,
      melodyInterval: 6,
      textureFilterFreq: 400,
      textureFilterQ: 1,
      textureGain: 0.1,
      shimmer: false,
      rhythmEnabled: false,
      reverbDecay: 5,
      reverbWet: 0.7,
      delayTime: 0.6,
      delayFeedback: 0.25,
      delayWet: 0.2,
    },
    visual: {
      skyPalette: [[5, 12, 35], [8, 25, 60], [3, 8, 25]],
      noisePalette: [[15, 40, 80]],
      noiseOpacity: 0.03,
      particlePalette: [[40, 120, 180], [20, 80, 140], [80, 160, 200]],
      flowScale: 0.002,
      flowSpeed: 0.00012,
      particleSpeed: 0.4,
      trailAlpha: 0.02,
      particleSize: 2.5,
      glowIntensity: 0.3,
      skyShiftSpeed: 0.0002,
    },
  },

  'northern-lights': {
    id: 'northern-lights',
    name: 'Northern Lights',
    description: 'Ethereal wonder',
    audio: {
      rootNote: 'E',
      scale: 'whole-tone',
      droneWaveform: 'triangle',
      droneGain: 0.14,
      droneDetune: 10,
      melodyGain: 0.07,
      melodyWaveform: 'sine',
      melodyOctaveLow: 3,
      melodyOctaveHigh: 5,
      melodyInterval: 4,
      textureFilterFreq: 800,
      textureFilterQ: 1.5,
      textureGain: 0.1,
      shimmer: true,
      rhythmEnabled: false,
      reverbDecay: 6,
      reverbWet: 0.8,
      delayTime: 0.5,
      delayFeedback: 0.35,
      delayWet: 0.35,
    },
    visual: {
      skyPalette: [[8, 15, 30], [10, 40, 35], [20, 10, 45]],
      noisePalette: [[20, 60, 50]],
      noiseOpacity: 0.05,
      particlePalette: [[50, 220, 140], [120, 80, 220], [60, 200, 220]],
      flowScale: 0.004,
      flowSpeed: 0.00025,
      particleSpeed: 1.0,
      trailAlpha: 0.025,
      particleSize: 2,
      glowIntensity: 0.5,
      skyShiftSpeed: 0.0004,
    },
  },

  'rain-garden': {
    id: 'rain-garden',
    name: 'Rain Garden',
    description: 'Gentle warmth',
    audio: {
      rootNote: 'G',
      scale: 'major-pentatonic',
      droneWaveform: 'sine',
      droneGain: 0.12,
      droneDetune: 5,
      melodyGain: 0.09,
      melodyWaveform: 'triangle',
      melodyOctaveLow: 4,
      melodyOctaveHigh: 5,
      melodyInterval: 3,
      textureFilterFreq: 600,
      textureFilterQ: 1.2,
      textureGain: 0.14,
      shimmer: false,
      rhythmEnabled: true,
      rhythmGain: 0.04,
      rhythmFilterFreq: 1200,
      rhythmDecay: 0.08,
      rhythmInterval: 0.35,
      reverbDecay: 3,
      reverbWet: 0.5,
      delayTime: 0.3,
      delayFeedback: 0.2,
      delayWet: 0.25,
    },
    visual: {
      skyPalette: [[15, 25, 15], [25, 40, 20], [20, 18, 10]],
      noisePalette: [[30, 50, 25]],
      noiseOpacity: 0.04,
      particlePalette: [[100, 180, 80], [180, 160, 60], [140, 200, 100]],
      flowScale: 0.003,
      flowSpeed: 0.0003,
      particleSpeed: 1.2,
      trailAlpha: 0.04,
      particleSize: 1.5,
      glowIntensity: 0.25,
      skyShiftSpeed: 0.0003,
    },
  },

  'stellar-drift': {
    id: 'stellar-drift',
    name: 'Stellar Drift',
    description: 'Cosmic contemplation',
    audio: {
      rootNote: 'Ab',
      scale: 'dorian',
      droneWaveform: 'sine',
      droneGain: 0.16,
      droneDetune: 12,
      melodyGain: 0.05,
      melodyWaveform: 'sine',
      melodyOctaveLow: 3,
      melodyOctaveHigh: 5,
      melodyInterval: 8,
      textureFilterFreq: 500,
      textureFilterQ: 0.8,
      textureGain: 0.08,
      shimmer: true,
      rhythmEnabled: false,
      reverbDecay: 7,
      reverbWet: 0.85,
      delayTime: 0.7,
      delayFeedback: 0.4,
      delayWet: 0.3,
    },
    visual: {
      skyPalette: [[8, 5, 20], [15, 8, 35], [5, 3, 15]],
      noisePalette: [[20, 15, 40]],
      noiseOpacity: 0.03,
      particlePalette: [[180, 160, 240], [240, 240, 255], [120, 100, 200]],
      flowScale: 0.002,
      flowSpeed: 0.0001,
      particleSpeed: 0.3,
      trailAlpha: 0.015,
      particleSize: 1,
      glowIntensity: 0.6,
      skyShiftSpeed: 0.00015,
    },
  },
};

export const SCENE_IDS = Object.keys(SCENES);
