// Canvas snapshot + share

export function captureScreenshot(canvas, sceneName = 'drift') {
  return new Promise((resolve) => {
    canvas.toBlob((blob) => {
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
      const filename = `drift-${sceneName}-${timestamp}.png`;

      // Download
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      a.click();
      URL.revokeObjectURL(url);

      resolve({ blob, filename });
    }, 'image/png');
  });
}

export async function shareScreenshot(canvas, sceneName = 'drift') {
  if (!navigator.share || !navigator.canShare) {
    return captureScreenshot(canvas, sceneName);
  }

  return new Promise((resolve) => {
    canvas.toBlob(async (blob) => {
      const file = new File([blob], `drift-${sceneName}.png`, { type: 'image/png' });

      try {
        await navigator.share({
          title: 'Drift',
          text: `A moment from "${sceneName}" — generated by Drift`,
          files: [file],
        });
        resolve({ shared: true });
      } catch {
        // User cancelled share — fall back to download
        resolve(captureScreenshot(canvas, sceneName));
      }
    }, 'image/png');
  });
}
